### ISSUE TITLE
Lab.js example links in README.md do not work

### ISSUE THREAD

**Issue by u01ai11** [Yury-Shevchenko/mad#3]
When I click through on the Lab.js links in the example they do not work! I just get taken to the Lab.js builder site with an empty project. 

I can see the lab.js url contains open-lab project, but nothing is loaded from there.

**Comment by Yury-Shevchenko** [comment]
Hello Alex! First, thanks a lot for reviewing the paper. 
I've just checked - the links work with me. 
Do you see a pop-up dialogue such as
"Would you like to load the study from https://open-lab.online/labjs/5ca3648b8ef62535954f9c50?"
It might be that dialogues are blocked in your browser. I would try different browser (specially, if you on a mac).

**Comment by u01ai11** [comment]
@Yury-Shevchenko Thanks -- it does work if I remove all my plugins from Chrome. 

I'll close the issue - but it might be good to put a note in your README so users will remember to do turn-off blockers etc.
