### ISSUE TITLE
I can't work out how to edit parameters in Open Lab

### ISSUE THREAD

**Issue by u01ai11** [Yury-Shevchenko/mad#4]
In the README it says: 
"The second option is to open the task in Open Lab, an online platform for deployment of experiments. To modify the task in lab.js or in Open Lab, you have to edit its parameters"

When I try and do this in Open Lab via the link (and after signing up -- this should also be mentioned in your documentation), I can only preview the example, I don't seem to have access to the JSON parameters -- as I can do easily in in Lab.js.

**Comment by Yury-Shevchenko** [comment]
Dear Alex,
Editing the parameters on Open Lab is realized through the study projects.  The user can change parameters of the task for each project. In this way, the original task remains unchanged, but users can create projects in which they use different versions of the task.
The documentation can be found here:
https://open-lab.online/docs/project
I will add the information about these steps to the README file.

**Comment by u01ai11** [comment]
Thanks! 

It would be good to go through the steps briefly (i.e. Signup -> New Study -> add MAD task in the study -> edit paramaters).

**Comment by Yury-Shevchenko** [comment]
The information about opening a task in Open lab and lab.js was added to the Readme file.
