### ISSUE TITLE
Missing doi from one reference

### ISSUE THREAD

**Issue by u01ai11** [Yury-Shevchenko/mad#7]
In paper.md there is a missing doi for the entry: 

"Reisen, N., Hoffrage, U., & Mast, F. W. (2008). Identifying decision strategies in a consumer choice situation. Judgment and decision making, 3(8), 641–658."

**Comment by Yury-Shevchenko** [comment]
This article does not have a doi. There is no doi on CrossRef or in other publications that cite this article. The article has been published in Judgment and Decision Making Journal (http://journal.sjdm.org/). The URL of the article is http://journal.sjdm.org/8801/jdm8801.html

**Comment by u01ai11** [comment]
Ok -- my bad !
